name: Checkstyle

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-check:
    uses: SpongePowered/.github/shared-workflows/check-style.yaml@master
    secrets: inherit
