name: Check Spotless

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-check:
    uses: SpongePowered/.github/.github/workflows/shared-check-spotless.yaml@2468a67a9364ca162db16564d96f5d559b45e095 # master
    secrets: inherit
