name: Check Spotless

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-check:
    uses: SpongePowered/.github/.github/workflows/shared-check-spotless.yaml@77240a8dfdf1b9049e4c9e2b038de35df915cd32 # master
    secrets: inherit
