name: Checkstyle

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-check:
    uses: SpongePowered/.github/.github/workflows/shared-check-style.yaml@8b5705969e169800a02b976a3d3f29745ee2fd3a # master
    secrets: inherit
