name: Build, Test, and Deploy

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

jobs:
  call-build:
    uses: SpongePowered/.github/shared-workflows/ci.yaml@master
    secrets: inherit
