name: Build, Test, and Deploy

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

jobs:
  call-build:
    uses: SpongePowered/.github/.github/workflows/shared-ci.yaml@77240a8dfdf1b9049e4c9e2b038de35df915cd32 # master
    secrets: inherit
