name: Build, Test, and Deploy

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

jobs:
  call-build:
    uses: SpongePowered/.github/.github/workflows/shared-ci.yaml@master
    secrets: inherit
