
name: Run Checkstyle

on:
  workflow_call:
    inputs:
      runtime_version:
        description: 'The default Java runtime version to run builds on'
        required: false
        type: number
        default: 11
      publishing_branch_regex:
        description: 'The regular expression to determine if a certain branch build should be published'
        required: false
        type: string
        default: 'master|main|trunk|(\d+\.(?:\d+\.)?x)'
      extra_gradle_params:
        description: 'Extra arguments to pass to all Gradle invocations'
        required: false
        type: string
        default: ''

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: "Setup JDK ${{ inputs.runtime_version }}"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "${{ inputs.runtime_version }}"
      # Checks branch name to see if we're going to potentially publish this
      - name: Check branch for publish
        uses: zml2008/action-regex-match@temp-deprecation-fix # fork, to be PR'd upstream
        id: branch-name
        with:
          text: ${{ github.ref }}
          regex: '^refs/heads/(?:${{ inputs.publishing_branch_regex }})$' # master or something like 0.8.x or 2.x

      # Run checkstyle checks, trying to execute all tasks even if some fail
      - name: Run Checkstyle Check
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: "${{ steps.branch-name.outputs.match == '' || github.event_name == 'pull_request' }}"
          arguments: --continue ${{ inputs.extra_gradle_params }} checkstyleAll
