name: "Validate Renovate Configuration"

on:
  push:
    paths:
    - "renovate-config.json"
  pull_request:
    paths:
    - "renovate-config.json"

jobs:
  validate:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
      with:
        config_file_path: renovate-config.json
